#!/usr/bin/env node
/**
 * airlock — sandboxed MCP runtime.
 *
 * `airlock run <server>` is what an MCP client invokes in place of the real
 * server command, so it must keep stdout clean for protocol traffic only.
 * Every other subcommand is an ordinary CLI and prints to stdout normally.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { homedir } from "node:os"
import { resolve } from "node:path"
import { loadConfig, type ServerPolicy } from "./config.js"
import { AuditLog, defaultLogPath, type AuditEvent } from "./audit.js"
import { runRelay } from "./relay.js"

const USAGE = `airlock — run MCP servers inside a Solari sandbox

usage:
  airlock run <server> [--config <path>]   relay a server (what your MCP client invokes)
  airlock init [--config <path>]           generate policy stubs from an existing MCP config
  airlock log [--server <name>] [--blocked] [--limit <n>]
  airlock policy [--config <path>]         show the effective policy

env:
  SOLARI_API_KEY   required by \`run\`
  AIRLOCK_LOG      audit log path (default ${defaultLogPath()})
`

function flag(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(`--${name}`)
  return i !== -1 ? argv[i + 1] : undefined
}
function has(argv: string[], name: string): boolean {
  return argv.includes(`--${name}`)
}

function describe(p: ServerPolicy): string {
  const egress = p.egress.length === 0 ? "none (no network at all)" : p.egress.join(", ")
  const mounts = p.mounts.length === 0 ? "none" : p.mounts.map((m) => `${m.path} (${m.mode})`).join(", ")
  return [
    `  launcher : ${p.launcher}`,
    `  package  : ${p.package}`,
    `  egress   : ${egress}`,
    `  mounts   : ${mounts}`,
    `  secrets  : ${Object.keys(p.secrets).length === 0 ? "none" : Object.keys(p.secrets).join(", ")}`,
    `  snapshot : ${p.snapshot ?? "(none yet — first run will provision)"}`,
  ].join("\n")
}

async function cmdRun(argv: string[]): Promise<number> {
  const name = argv[0]
  if (!name || name.startsWith("--")) {
    process.stderr.write("airlock run: a server name is required\n")
    return 2
  }
  const apiKey = process.env.SOLARI_API_KEY
  if (!apiKey) {
    process.stderr.write("airlock: SOLARI_API_KEY is not set\n")
    return 2
  }
  const config = loadConfig(flag(argv, "config"))
  const policy = config.servers[name]
  if (!policy) {
    const known = Object.keys(config.servers).join(", ") || "(none)"
    process.stderr.write(`airlock: no [server.${name}] in ${config.path}. Known servers: ${known}\n`)
    return 2
  }
  const audit = new AuditLog(process.env.AIRLOCK_LOG ?? defaultLogPath())
  return runRelay({ policy, apiKey, audit })
}

/**
 * Read an existing Claude Code / Cursor MCP config and emit policy stubs
 * (SPEC §6.1). Egress and mounts are deliberately left empty: the safe default
 * is nothing, and the user opts in per server.
 */
async function cmdInit(argv: string[]): Promise<number> {
  const configPath = resolve(flag(argv, "config") ?? "airlock.toml")
  if (existsSync(configPath) && !has(argv, "force")) {
    process.stderr.write(`airlock init: ${configPath} already exists (use --force to overwrite)\n`)
    return 1
  }

  const candidates = [
    resolve(homedir(), ".claude.json"),
    resolve(homedir(), ".config/claude/mcp.json"),
    resolve(homedir(), ".cursor/mcp.json"),
    resolve(".mcp.json"),
  ]
  type McpEntry = { command?: string; args?: string[] }
  const discovered: Record<string, McpEntry> = {}
  const sources: string[] = []

  for (const candidate of candidates) {
    if (!existsSync(candidate)) continue
    try {
      const parsed = JSON.parse(readFileSync(candidate, "utf8")) as {
        mcpServers?: Record<string, McpEntry>
        projects?: Record<string, { mcpServers?: Record<string, McpEntry> }>
      }
      const found = { ...parsed.mcpServers }
      for (const project of Object.values(parsed.projects ?? {})) {
        Object.assign(found, project.mcpServers)
      }
      if (Object.keys(found).length > 0) {
        Object.assign(discovered, found)
        sources.push(candidate)
      }
    } catch {
      process.stderr.write(`airlock init: could not parse ${candidate}, skipping\n`)
    }
  }

  const blocks: string[] = [
    "# Generated by `airlock init`.",
    "#",
    "# Isolation is the default; access is the opt-in. An omitted `egress` means",
    "# no network at all, and an omitted `mounts` means the server sees none of",
    "# your filesystem. Add only what a server genuinely needs.",
    "",
  ]
  if (sources.length > 0) blocks.push(`# Discovered from: ${sources.join(", ")}`, "")

  for (const [name, entry] of Object.entries(discovered)) {
    const args = entry.args ?? []
    // `npx -y <pkg>` → package is the first non-flag argument.
    const pkg = args.find((a) => !a.startsWith("-")) ?? ""
    const launcher = entry.command === "npx" ? "npx" : entry.command?.includes("python") ? "python" : "npx"
    blocks.push(
      `[server.${name}]`,
      `launcher = ${JSON.stringify(launcher)}`,
      `package  = ${JSON.stringify(pkg)}`,
      `egress   = []   # e.g. ["api.github.com"]`,
      `mounts   = []   # e.g. [{ path = "~/projects/demo", mode = "rw" }]`,
      "",
    )
  }

  if (Object.keys(discovered).length === 0) {
    blocks.push(
      "# No existing MCP config found. Here is a starting point:",
      "#",
      '# [server.everything]',
      '# launcher = "npx"',
      '# package  = "@modelcontextprotocol/server-everything"',
      "# egress   = []",
      "# mounts   = []",
      "",
    )
  }

  writeFileSync(configPath, blocks.join("\n"))
  process.stdout.write(`wrote ${configPath}\n`)
  if (Object.keys(discovered).length > 0) {
    process.stdout.write(`found ${Object.keys(discovered).length} server(s): ${Object.keys(discovered).join(", ")}\n`)
    process.stdout.write("\nReview the egress and mounts for each, then point your MCP client at:\n")
    const first = Object.keys(discovered)[0]
    process.stdout.write(`  { "command": "airlock", "args": ["run", "${first}"] }\n`)
  }
  return 0
}

function cmdLog(argv: string[]): number {
  const events = AuditLog.read(process.env.AIRLOCK_LOG ?? defaultLogPath())
  const server = flag(argv, "server")
  const blockedOnly = has(argv, "blocked")
  const limit = Number(flag(argv, "limit") ?? 50)

  let filtered = events
  if (server) filtered = filtered.filter((e) => e.server === server)
  if (blockedOnly) filtered = filtered.filter((e) => e.kind === "net.attempt" && !e.allowed)

  if (filtered.length === 0) {
    process.stdout.write("no matching audit events\n")
    return 0
  }

  for (const e of filtered.slice(-limit)) {
    process.stdout.write(render(e) + "\n")
  }
  return 0
}

function render(e: AuditEvent): string {
  const ts = e.at.replace("T", " ").replace(/\.\d+Z$/, "")
  switch (e.kind) {
    case "session.start":
      return `${ts}  ${e.server}  session.start  egress=[${e.egress.join(",")}] mounts=[${e.mounts.join(",")}]`
    case "session.end":
      return `${ts}  ${e.server}  session.end    ${e.durationMs}ms exit=${e.exitCode ?? "?"}`
    case "tool.call":
      return `${ts}  ${e.server}  tool.call      ${e.tool} args=${e.argsDigest} (${e.argsBytes}B)`
    case "tool.result":
      return `${ts}  ${e.server}  tool.result    ${e.tool} ${e.durationMs}ms ${e.resultBytes}B${e.isError ? " ERROR" : ""}`
    case "net.attempt":
      return `${ts}  ${e.server}  net.${e.allowed ? "allow " : "BLOCK "}    ${e.host}`
    case "rpc":
      return `${ts}  ${e.server}  rpc            ${e.direction} ${e.method} ${e.bytes}B`
    case "warn":
      return `${ts}  ${e.server}  warn           ${e.message}`
  }
}

function cmdPolicy(argv: string[]): number {
  const config = loadConfig(flag(argv, "config"))
  process.stdout.write(`${config.path}\n\n`)
  for (const [name, policy] of Object.entries(config.servers)) {
    process.stdout.write(`[server.${name}]\n${describe(policy)}\n\n`)
  }
  return 0
}

async function main(): Promise<number> {
  const [, , command, ...rest] = process.argv
  switch (command) {
    case "run":
      return cmdRun(rest)
    case "init":
      return cmdInit(rest)
    case "log":
      return cmdLog(rest)
    case "policy":
      return cmdPolicy(rest)
    case undefined:
    case "-h":
    case "--help":
      process.stdout.write(USAGE)
      return 0
    default:
      process.stderr.write(`airlock: unknown command ${JSON.stringify(command)}\n\n${USAGE}`)
      return 2
  }
}

main()
  .then((code) => process.exit(code))
  .catch((err) => {
    process.stderr.write(`airlock: ${err instanceof Error ? err.message : String(err)}\n`)
    process.exit(1)
  })
